spring.application.name=crud-testes
spring.datasource.url=jdbc:postgresql://ep-polished-snow-ad5r57wi-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lFcOs5VA1mWE
#spring.h2.console.enabled=true
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update